apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brahmanyasudulagunta/gitops-prod
    targetRevision: HEAD
    path: environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
