apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ashrith2727/backend-gitops:v1
        env:
        - name: DATABASE_URL
          value: postgresql://krishna:1729@postgres:5432/postgresdb
        - name: SECRET_KEY
          value: "gitops-secret-2026"
        - name: ALGORITHM
          value: HS256
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "1440"
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  selector:
    app: backend
  ports:
  - port: 8002
    targetPort: 8002
