apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop-canary
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops
      track: canary
  template:
    metadata:
      labels:
        app: gitops
        track: canary
    spec:
      serviceAccountName: gitops-sa
      containers:
      - name: app
        image: ashrith2727/gitops:39
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
